server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heqing?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# JWT配置
jwt:
  secret: hotelManagementSecretKey
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    root: INFO
    com.hotel: DEBUG
  file:
    name: logs/hotel-management.log